### PR TITLE
new classs added......

### PR DESCRIPTION
**Pull request by kaman85**
Hi
 I have commited MyLocalWork with new classes, Please review and approved

### CODE REVIEW

**Comment by Khosruz** [comment]
hi Khos your code looks good please do one more check

regards 
Boss

**Comment by kaman85** [comment]
Please find the solution

**Comment by Khosruz** [comment]
i think you need to added condition insted of || to &&

**Comment by kaman85** [comment]
Hi i have added additional add, Please aproved

**Comment by Khosruz** [comment]
Hi Khosruz its looks good, go ahead and marg to master branch

**Comment by Khosruz** [comment]
Perfact, go and mearge

**Pull request merged**
